# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: test
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go 
    
    - name: Check out code into the Go midule directory 
      uses: actions/checkout@v2

    
    - name: Test
      run: go test -v ./...
